### ISSUE TITLE
Pipelines sometipes fail with "Error grabbing Grapes"

### ISSUE THREAD

**Issue by nikarh** [agilestacks/jenkins#2]
Possible causes:

- Network error corrupts cache. This is possible since sometimes this error happens only with a single build run simultaneously
- Race condition. Links:
   - [https://issues.apache.org/jira/browse/GROOVY-8097](https://issues.apache.org/jira/browse/GROOVY-8097)
   - [https://issues.jenkins-ci.org/browse/JENKINS-42307](https://issues.jenkins-ci.org/browse/JENKINS-42307)
   - [https://issues.apache.org/jira/browse/GROOVY-7407](https://issues.apache.org/jira/browse/GROOVY-7407)
   - [https://issues.jenkins-ci.org/browse/JENKINS-48974](https://issues.jenkins-ci.org/browse/JENKINS-48974)

**Comment by akranga** [comment]
My observations shows this is not a network problem, which however has been my first suspec

**Comment by akranga** [comment]
With commit `#58301fd` removed @Grab from shared library
